export enum WorkOrderStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ASSIGNED = 'ASSIGNED',
  UPDATED = 'UPDATED',
  WAITING_SPAREPART_APPROVAL = 'WAITING_SPAREPART_APPROVAL',
  READY_TO_WORK = 'READY_TO_WORK',
  WORKING = 'WORKING',
  COMPLETED = 'COMPLETED',
}
